servers:
- url: http://localhost
  description: "Local server"
models:
- modelName: gppdb
  collectionId: gppdb
  standards: [Features,Catalogue]
activeStandards:
- pathToDoc: ../standards/Features/docFragment.yaml
  standard: Features
- pathToDoc: ./main.yaml
  standard: Template