allcrs:
- uri: "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
  srid: 4326
  authority: OGC
  isGeographic: false
- uri: "http://www.opengis.net/def/crs/EPSG/0/4326"
  srid: 4326
  authority: EPSG
  isGeographic: true
trs: "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"


standards:
- standard: 'features'
  pathToDoc: ../standards/features/index.yaml
  defaultOptions:
    crs: 
      $ref: '#/allcrs'
    trs: 
      $ref: '#/trs'
  collections:
  - modelName: gtdb
    collectionId: gtdb
    license: 
      title: 'EULA'
      href: https://www.start.umd.edu/gtd/terms-of-use/